import { User, Checkup, SymptomLog, PreventionProtocol, AIPrediction } from "@/types/models";

export const mockUser: User = {
  id: "usr_001",
  name: "Alex Johnson",
  email: "alex.johnson@email.com",
  age: 32,
  gender: "male",
};

export const mockCheckups: Checkup[] = [
  {
    id: "chk_001",
    date: "2026-03-20",
    bmiData: { height: 175, weight: 82, score: 26.8, category: "Overweight" },
    bloodReport: {
      hemoglobin: 13.5,
      fastingSugar: 118,
      totalCholesterol: 225,
      hdl: 42,
      ldl: 148,
      triglycerides: 175,
      creatinine: 1.0,
      tsh: 3.2,
    },
    aiPredictions: [
      { riskTag: "Pre-Diabetes", riskLevel: "high", confidence: 0.82, description: "Fasting sugar levels indicate pre-diabetic range. Combined with elevated BMI, risk of Type 2 Diabetes is significant." },
      { riskTag: "Dyslipidemia", riskLevel: "medium", confidence: 0.74, description: "LDL cholesterol and triglycerides are above optimal ranges, increasing cardiovascular risk." },
    ],
    preventionPlan: [
      {
        conditionTag: "Pre-Diabetes",
        title: "Type 2 Diabetes Prevention Plan",
        dietSteps: ["Reduce refined carbohydrate intake by 40%", "Increase dietary fiber to 30g/day (whole grains, legumes, vegetables)", "Replace sugary beverages with water or herbal teas", "Follow a Mediterranean-style eating pattern", "Limit processed food consumption"],
        exerciseSteps: ["150 minutes/week of moderate aerobic activity (brisk walking, cycling)", "Include 2-3 sessions of resistance training per week", "Take a 15-minute walk after each major meal", "Aim for 8,000-10,000 steps daily"],
        monitoringSteps: ["Check fasting blood glucose monthly", "HbA1c test every 3 months", "Track weight weekly", "Monitor blood pressure bi-weekly"],
        medicalDisclaimer: "This plan is generated by AI for educational purposes only. Consult your physician before making any changes to your diet or exercise routine.",
      },
      {
        conditionTag: "Dyslipidemia",
        title: "Cholesterol Management Plan",
        dietSteps: ["Increase omega-3 fatty acid intake (fish, walnuts, flaxseeds)", "Limit saturated fat to <7% of daily calories", "Add plant sterols/stanols (2g/day)", "Consume more soluble fiber (oats, beans, citrus fruits)"],
        exerciseSteps: ["30 minutes of aerobic exercise 5 days/week", "Include high-intensity interval training 2x/week", "Yoga or stretching for stress management"],
        monitoringSteps: ["Full lipid panel every 3 months", "Track dietary patterns using a food journal", "Annual cardiovascular risk assessment"],
        medicalDisclaimer: "This plan is generated by AI for educational purposes only. Consult your physician or cardiologist for personalized lipid management.",
      },
    ],
  },
  {
    id: "chk_002",
    date: "2025-12-15",
    bmiData: { height: 175, weight: 85, score: 27.8, category: "Overweight" },
    bloodReport: {
      hemoglobin: 13.2,
      fastingSugar: 125,
      totalCholesterol: 235,
      hdl: 40,
      ldl: 155,
      triglycerides: 185,
      creatinine: 1.1,
      tsh: 3.5,
    },
    aiPredictions: [
      { riskTag: "Pre-Diabetes", riskLevel: "high", confidence: 0.87, description: "Elevated fasting sugar with upward trend." },
    ],
    preventionPlan: [],
  },
];

export const mockSymptomLogs: SymptomLog[] = [
  {
    id: "sym_001",
    date: "2026-03-22",
    rawText: "I've been having a persistent headache for 3 days, feeling very tired and my throat is sore. I also have a mild fever.",
    extractedSymptoms: ["persistent headache", "fatigue", "sore throat", "mild fever"],
    predictedIllness: "Upper Respiratory Tract Infection (Common Cold/Flu)",
    triageAdvice: {
      level: "self-care",
      message: "Your symptoms are consistent with a common viral upper respiratory infection. Rest and home care should be sufficient.",
      homeRemedies: ["Rest and get adequate sleep (8+ hours)", "Stay hydrated — drink warm water, herbal tea, or broth", "Gargle with warm salt water for sore throat", "Use over-the-counter pain relievers for headache (as directed)", "Monitor temperature; if fever exceeds 103°F (39.4°C), consult a doctor"],
    },
  },
  {
    id: "sym_002",
    date: "2026-03-18",
    rawText: "I have severe chest pain that radiates to my left arm, shortness of breath, and I feel dizzy.",
    extractedSymptoms: ["severe chest pain", "pain radiating to left arm", "shortness of breath", "dizziness"],
    predictedIllness: "Possible Cardiac Event — Myocardial Infarction",
    triageAdvice: {
      level: "emergency",
      message: "⚠️ EMERGENCY: Your symptoms are consistent with a possible heart attack. Call emergency services (911) IMMEDIATELY. Do not drive yourself to the hospital.",
      homeRemedies: ["Call 911 or your local emergency number IMMEDIATELY", "Chew one aspirin (325mg) if not allergic", "Sit upright in a comfortable position", "Loosen any tight clothing", "Do NOT exert yourself physically"],
    },
  },
];

export const mockPredictions: AIPrediction[] = [
  { riskTag: "Type 2 Diabetes", riskLevel: "high", confidence: 0.82, description: "Elevated fasting sugar and BMI indicate significant risk." },
  { riskTag: "Cardiovascular Disease", riskLevel: "medium", confidence: 0.65, description: "Lipid profile suggests moderate cardiovascular risk." },
  { riskTag: "Thyroid Dysfunction", riskLevel: "low", confidence: 0.3, description: "TSH levels are within normal range." },
];
